name: Build Go Backend Docker Image

on:
  push:
    branches:
      - main # O il nome del tuo branch principale

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Sarà qualcosa come 'tuo-utente/tuo-repo'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Cruciale per pushare su GHCR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata (Tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
            type=raw,value=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: . # Il contesto di build è la root del repository
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Migliora la velocità delle build successive
          cache-to: type=gha,mode=max
